In [1]:
! pip install -q kaggle

In [2]:
from google.colab import files

files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"amirebrahiminasab","key":"f5ea3a6c93484c7a343c4382559fb1c5"}'}

In [3]:
! chmod 600 ~/.kaggle/kaggle.json

chmod: cannot access '/root/.kaggle/kaggle.json': No such file or directory


In [4]:
!kaggle datasets download -d venky73/spam-mails-dataset

Dataset URL: https://www.kaggle.com/datasets/venky73/spam-mails-dataset
License(s): CC0-1.0
  0% 0.00/1.86M [00:00<?, ?B/s]
100% 1.86M/1.86M [00:00<00:00, 169MB/s]


In [5]:
!unzip spam-mails-dataset.zip

Archive:  spam-mails-dataset.zip
  inflating: spam_ham_dataset.csv    


In [6]:
import pandas as pd

In [9]:
data_frame = pd.read_csv("spam_ham_dataset.csv")
data_frame

Unnamed: 0 label                                               text  \
0            605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1           2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2           3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3           4685  spam  Subject: photoshop , windows , office . cheap ...   
4           2030   ham  Subject: re : indian springs\r\nthis deal is t...   
...          ...   ...                                                ...   
5166        1518   ham  Subject: put the 10 on the ft\r\nthe transport...   
5167         404   ham  Subject: 3 / 4 / 2000 and following noms\r\nhp...   
5168        2933   ham  Subject: calpine daily gas nomination\r\n>\r\n...   
5169        1409   ham  Subject: industrial worksheets for august 2000...   
5170        4807  spam  Subject: important online banking alert\r\ndea...   

      label_num  
0             0  
1             0  
2             0  
3             1  
4             0  
...         ...  
5166          0  
5167          0  
5168          0  
5169          0  
5170          1  

[5171 rows x 4 columns]

In [56]:
labels = list(data_frame['label_num'])
labels

[0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,


In [13]:
ls = list(data_frame["text"])
ls

["Subject: enron methanol ; meter # : 988291\r\nthis is a follow up to the note i gave you on monday , 4 / 3 / 00 { preliminary\r\nflow data provided by daren } .\r\nplease override pop ' s daily volume { presently zero } to reflect daily\r\nactivity you can obtain from gas control .\r\nthis change is needed asap for economics purposes .",
 'Subject: hpl nom for january 9 , 2001\r\n( see attached file : hplnol 09 . xls )\r\n- hplnol 09 . xls',
 "Subject: neon retreat\r\nho ho ho , we ' re around to that most wonderful time of the year - - - neon leaders retreat time !\r\ni know that this time of year is extremely hectic , and that it ' s tough to think about anything past the holidays , but life does go on past the week of december 25 through january 1 , and that ' s what i ' d like you to think about for a minute .\r\non the calender that i handed out at the beginning of the fall semester , the retreat was scheduled for the weekend of january 5 - 6 . but because of a youth ministers c

In [14]:
len(ls)

5171

In [18]:
cleaned_ls = [ls[idx].replace('\r\n', ' ') for idx in range(len(ls))]
cleaned_ls

["Subject: enron methanol ; meter # : 988291 this is a follow up to the note i gave you on monday , 4 / 3 / 00 { preliminary flow data provided by daren } . please override pop ' s daily volume { presently zero } to reflect daily activity you can obtain from gas control . this change is needed asap for economics purposes .",
 'Subject: hpl nom for january 9 , 2001 ( see attached file : hplnol 09 . xls ) - hplnol 09 . xls',
 "Subject: neon retreat ho ho ho , we ' re around to that most wonderful time of the year - - - neon leaders retreat time ! i know that this time of year is extremely hectic , and that it ' s tough to think about anything past the holidays , but life does go on past the week of december 25 through january 1 , and that ' s what i ' d like you to think about for a minute . on the calender that i handed out at the beginning of the fall semester , the retreat was scheduled for the weekend of january 5 - 6 . but because of a youth ministers conference that brad and dustin

In [42]:
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator


tokenizer = get_tokenizer("basic_english")


def yield_tokens(data_iter):
    for text in data_iter:
        yield tokenizer(text)


vocab = build_vocab_from_iterator(yield_tokens(cleaned_ls), specials=['<pad>'])
vocab.set_default_index(vocab['<pad>'])
print("Vocabulary:", vocab.get_stoi())

Vocabulary: {'zzocb': 50520, 'zzo': 50519, 'zzn': 50518, 'zzezrjok': 50517, 'zyrtec': 50515, 'zynsdirnh': 50512, 'zykfe': 50510, 'zyjvit': 50509, 'zxzmcnbf': 50508, 'zxklh': 50507, 'zwu': 50501, 'zwoegen': 50500, 'zwmdjvr': 50499, 'zwdm': 50497, 'zvx': 50496, 'zvrkxjmex': 50495, 'zvikydqu': 50492, 'zve': 50491, 'zux': 50488, 'zustellung': 50487, 'zustande': 50486, 'zusammenhang': 50485, 'zusagen': 50484, 'zupymv': 50483, 'zum': 50481, 'zukin': 50480, 'zuidholland': 50478, 'zuid': 50477, 'zufferli': 50474, 'ztv': 50471, 'ztuje': 50470, 'ztqpk': 50468, 'ztolu': 50466, 'ztnjcl': 50465, 'ztljrg': 50464, 'ztletgfk': 50463, 'zszr': 50462, 'zsuawvswl': 50458, 'zsoxlasv': 50457, 'zsgvjwl': 50453, 'zscmiybr': 50452, 'zrwkd': 50450, 'zrlmtbr': 50448, 'zrlhtrfa': 50447, 'zrejig': 50445, 'zravgcllqke': 50443, 'zquokka': 50442, 'zqthsqmz': 50441, 'zqt': 50440, 'zqmjcz': 50438, 'zqlzaeqau': 50437, 'zql': 50436, 'zpocyelie': 50432, 'zpgbk': 50430, 'zpfrenckv': 50428, 'zpbs': 50427, 'zorn': 50421, 'zo

In [43]:
len(vocab)

50523

In [41]:
max_len = max(len(s) for s in cleaned_ls)
max_len

1594

In [48]:
import torch
import torch.nn as nn

In [50]:
emails = []

for s in cleaned_ls:
  tokens = tokenizer(s)
  indices = torch.tensor([vocab[token] for token in tokens])

  padded_indices = nn.functional.pad(indices, (0, max_len - len(indices)), value=vocab["<pad>"])

  emails.append(padded_indices)



In [53]:
emails

[tensor([ 14,  22, 913,  ...,   0,   0,   0]),
 tensor([ 14,  63, 157,  ...,   0,   0,   0]),
 tensor([  14, 1382, 7830,  ...,    0,    0,    0]),
 tensor([  14, 1318,    4,  ...,    0,    0,    0]),
 tensor([  14,   71, 5418,  ...,    0,    0,    0]),
 tensor([  14, 3112,  550,  ...,    0,    0,    0]),
 tensor([  14, 1495, 1297,  ...,    0,    0,    0]),
 tensor([ 14, 322,  10,  ...,   0,   0,   0]),
 tensor([ 14, 333,   3,  ...,   0,   0,   0]),
 tensor([ 14, 553,  10,  ...,   0,   0,   0]),
 tensor([   14, 48758,    81,  ...,     0,     0,     0]),
 tensor([   14,   194, 24201,  ...,     0,     0,     0]),
 tensor([14, 22,  3,  ...,  0,  0,  0]),
 tensor([  14, 6677,    2,  ...,    0,    0,    0]),
 tensor([ 14, 273, 373,  ...,   0,   0,   0]),
 tensor([   14, 23744,   431,  ...,  5321,    20,   112]),
 tensor([ 14,  71, 228,  ...,   0,   0,   0]),
 tensor([  14, 1812,    1,  ...,    0,    0,    0]),
 tensor([  14,   57, 3353,  ...,    0,    0,    0]),
 tensor([  14,  466, 6153,  .

In [123]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(emails, labels, test_size=0.4, random_state = 42)

In [124]:
email_label_pairs = [(x_train[idx], y_train[idx]) for idx in range(len(x_train))]

In [125]:
from torch.utils.data import Dataset, DataLoader
import torch.optim as optim

In [126]:
class SpamEmailDataset(Dataset):
    def __init__(self, email_label_pairs, vocab, max_seq_length):
        self.email_label_pairs = email_label_pairs
        self.vocab = vocab
        self.max_seq_length = max_seq_length

    def __len__(self):
        return len(self.email_label_pairs)

    def __getitem__(self, idx):
        email, label = self.email_label_pairs[idx]
        # email_tensor = torch.tensor(email, dtype=torch.long)
        label = torch.tensor(label, dtype=torch.long)

        return email, label



dataset = SpamEmailDataset(email_label_pairs, vocab, max_len)


In [127]:
dataloader = DataLoader(dataset, batch_size=16, shuffle=True)

## Let's try it without DropOut.

In [148]:
class SpamDetectorModel(nn.Module):
  def __init__(self, embed_size) -> None:
    super(SpamDetectorModel, self).__init__()
    self.embedding = nn.Embedding(len(vocab), embed_size)
    self.lstm = nn.LSTM(embed_size, 64, batch_first=True)
    self.fc = nn.Linear(64, 32)
    self.relu = nn.ReLU()
    self.out = nn.Linear(32, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, x):
    embedded = self.embedding(x)
    lstm_out, _ = self.lstm(embedded)
    pooled = torch.max(lstm_out, 1)[0]
    fc = self.fc(pooled)
    out = self.out(fc)

    return self.sigmoid(out)



model = SpamDetectorModel(150)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = model.to(device)

In [149]:
model.train()

SpamDetectorModel(
  (embedding): Embedding(50523, 150)
  (lstm): LSTM(150, 64, batch_first=True)
  (fc): Linear(in_features=64, out_features=32, bias=True)
  (relu): ReLU()
  (out): Linear(in_features=32, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [150]:
num_epoch = 30

for _ in range(num_epoch):
  correct_label, total_label = 0, 0
  for email, label in dataloader:
    email, label = email.to(device), label.to(device)

    output = model(email)

    predicted = (output.squeeze() > 0.5).float()
    total_label += label.size(0)
    correct_label += (predicted == label).sum().item()

    loss = criterion(output.squeeze(), label.float())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  print(f"Train Accuracy on {_+1} epoch is: {100*correct_label / total_label}%.")
  if correct_label / total_label == 1.0:
    break


Train Accuracy on 1 epoch is: 79.98065764023211%.
Train Accuracy on 2 epoch is: 97.93681495809156%.
Train Accuracy on 3 epoch is: 99.54867827208253%.
Train Accuracy on 4 epoch is: 99.93552546744036%.
Train Accuracy on 5 epoch is: 100.0%.


In [151]:
test_email_label_pairs = [(x_test[idx], y_test[idx]) for idx in range(len(x_test))]

test_dataset = SpamEmailDataset(test_email_label_pairs, vocab, max_len)

test_dataloader = DataLoader(test_dataset, batch_size=16, shuffle=True)

In [152]:
model.eval()

total_label, correct_label = 0, 0

with torch.no_grad():
  for email, label in test_dataloader:
      email, label = email.to(device), label.to(device)

      output = model(email)
      predicted = (output.squeeze() > 0.5).float()
      total_label += label.size(0)
      correct_label += (predicted == label).sum().item()


print(f"Test Accuracy is: {100 * correct_label / total_label}%")


Test Accuracy is: 98.06669888835187%


## Let's try with DropOut

In [183]:
class SpamDetectorModelWithDropOut(nn.Module):
  def __init__(self, embed_size) -> None:
    super(SpamDetectorModelWithDropOut, self).__init__()
    self.embedding = nn.Embedding(len(vocab), embed_size)
    self.lstm = nn.LSTM(embed_size, 64, batch_first=True)
    self.fc = nn.Linear(64, 32)
    self.relu = nn.ReLU()
    self.drop = nn.Dropout(0.6)
    self.out = nn.Linear(32, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, x):
    embedded = self.embedding(x)
    lstm_out, _ = self.lstm(embedded)
    pooled = torch.max(lstm_out, 1)[0]
    pooled = self.drop(pooled)
    fc = self.fc(pooled)
    fc = self.drop(fc)
    out = self.out(fc)

    return self.sigmoid(out)



model = SpamDetectorModelWithDropOut(150)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = model.to(device)

In [184]:
model.train()

SpamDetectorModelWithDropOut(
  (embedding): Embedding(50523, 150)
  (lstm): LSTM(150, 64, batch_first=True)
  (fc): Linear(in_features=64, out_features=32, bias=True)
  (relu): ReLU()
  (drop): Dropout(p=0.6, inplace=False)
  (out): Linear(in_features=32, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [185]:
num_epoch = 18

for _ in range(num_epoch):
  correct_label, total_label = 0, 0
  for email, label in dataloader:
    email, label = email.to(device), label.to(device)

    output = model(email)

    predicted = (output.squeeze() > 0.5).float()
    total_label += label.size(0)
    correct_label += (predicted == label).sum().item()

    loss = criterion(output.squeeze(), label.float())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  print(f"Train Accuracy on {_+1} epoch is: {100*correct_label / total_label}%.")
  if correct_label / total_label == 1.0:
    break


Train Accuracy on 1 epoch is: 68.56866537717602%.
Train Accuracy on 2 epoch is: 85.1063829787234%.
Train Accuracy on 3 epoch is: 94.58413926499033%.
Train Accuracy on 4 epoch is: 97.48549323017409%.
Train Accuracy on 5 epoch is: 98.61379754996776%.
Train Accuracy on 6 epoch is: 99.35525467440361%.
Train Accuracy on 7 epoch is: 98.03352675693101%.
Train Accuracy on 8 epoch is: 99.29078014184397%.
Train Accuracy on 9 epoch is: 99.74210186976144%.
Train Accuracy on 10 epoch is: 99.87105093488073%.
Train Accuracy on 11 epoch is: 99.93552546744036%.
Train Accuracy on 12 epoch is: 100.0%.


In [186]:
test_email_label_pairs = [(x_test[idx], y_test[idx]) for idx in range(len(x_test))]

test_dataset = SpamEmailDataset(test_email_label_pairs, vocab, max_len)

test_dataloader = DataLoader(test_dataset, batch_size=16, shuffle=True)

In [187]:
model.eval()

total_label, correct_label = 0, 0

with torch.no_grad():
  for email, label in test_dataloader:
      email, label = email.to(device), label.to(device)

      output = model(email)
      predicted = (output.squeeze() > 0.5).float()
      total_label += label.size(0)
      correct_label += (predicted == label).sum().item()


print(f"Test Accuracy is: {100 * correct_label / total_label}%")


Test Accuracy is: 98.11503141614307%


## Let's try without the fc layer.

In [191]:
class SpamDetectorModelWithoutFc(nn.Module):
  def __init__(self, embed_size) -> None:
    super(SpamDetectorModelWithoutFc, self).__init__()
    self.embedding = nn.Embedding(len(vocab), embed_size)
    self.lstm = nn.LSTM(embed_size, 64, batch_first=True)
    # self.drop = nn.Dropout(0.6)
    self.out = nn.Linear(64, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, x):
    embedded = self.embedding(x)
    lstm_out, _ = self.lstm(embedded)
    pooled = torch.max(lstm_out, 1)[0]
    # pooled = self.drop(pooled)
    out = self.out(pooled)

    return self.sigmoid(out)



model = SpamDetectorModelWithoutFc(150)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = model.to(device)
model.train()

SpamDetectorModelWithoutFc(
  (embedding): Embedding(50523, 150)
  (lstm): LSTM(150, 64, batch_first=True)
  (out): Linear(in_features=64, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [192]:
num_epoch = 18

for _ in range(num_epoch):
  correct_label, total_label = 0, 0
  for email, label in dataloader:
    email, label = email.to(device), label.to(device)

    output = model(email)

    predicted = (output.squeeze() > 0.5).float()
    total_label += label.size(0)
    correct_label += (predicted == label).sum().item()

    loss = criterion(output.squeeze(), label.float())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  print(f"Train Accuracy on {_+1} epoch is: {100*correct_label / total_label}%.")
  if correct_label / total_label == 1.0:
    break


Train Accuracy on 1 epoch is: 77.78852353320438%.
Train Accuracy on 2 epoch is: 93.61702127659575%.
Train Accuracy on 3 epoch is: 96.67956157317859%.
Train Accuracy on 4 epoch is: 98.1947130883301%.
Train Accuracy on 5 epoch is: 99.35525467440361%.
Train Accuracy on 6 epoch is: 99.64539007092199%.
Train Accuracy on 7 epoch is: 99.90328820116054%.
Train Accuracy on 8 epoch is: 98.58156028368795%.
Train Accuracy on 9 epoch is: 99.5164410058027%.
Train Accuracy on 10 epoch is: 99.8388136686009%.
Train Accuracy on 11 epoch is: 99.96776273372018%.
Train Accuracy on 12 epoch is: 100.0%.


In [193]:
test_email_label_pairs = [(x_test[idx], y_test[idx]) for idx in range(len(x_test))]

test_dataset = SpamEmailDataset(test_email_label_pairs, vocab, max_len)

test_dataloader = DataLoader(test_dataset, batch_size=16, shuffle=True)

In [194]:
model.eval()

total_label, correct_label = 0, 0

with torch.no_grad():
  for email, label in test_dataloader:
      email, label = email.to(device), label.to(device)

      output = model(email)
      predicted = (output.squeeze() > 0.5).float()
      total_label += label.size(0)
      correct_label += (predicted == label).sum().item()


print(f"Test Accuracy is: {100 * correct_label / total_label}%")


Test Accuracy is: 97.87336877718705%


# Now let's try it without 100% accuracy on training dataset.

## Let's try it without DropOut.

In [195]:
class SpamDetectorModel(nn.Module):
  def __init__(self, embed_size) -> None:
    super(SpamDetectorModel, self).__init__()
    self.embedding = nn.Embedding(len(vocab), embed_size)
    self.lstm = nn.LSTM(embed_size, 64, batch_first=True)
    self.fc = nn.Linear(64, 32)
    self.relu = nn.ReLU()
    self.out = nn.Linear(32, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, x):
    embedded = self.embedding(x)
    lstm_out, _ = self.lstm(embedded)
    pooled = torch.max(lstm_out, 1)[0]
    fc = self.fc(pooled)
    out = self.out(fc)

    return self.sigmoid(out)



model = SpamDetectorModel(150)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = model.to(device)

In [196]:
model.train()

SpamDetectorModel(
  (embedding): Embedding(50523, 150)
  (lstm): LSTM(150, 64, batch_first=True)
  (fc): Linear(in_features=64, out_features=32, bias=True)
  (relu): ReLU()
  (out): Linear(in_features=32, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [197]:
num_epoch = 30

for _ in range(num_epoch):
  correct_label, total_label = 0, 0
  for email, label in dataloader:
    email, label = email.to(device), label.to(device)

    output = model(email)

    predicted = (output.squeeze() > 0.5).float()
    total_label += label.size(0)
    correct_label += (predicted == label).sum().item()

    loss = criterion(output.squeeze(), label.float())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  print(f"Train Accuracy on {_+1} epoch is: {100*correct_label / total_label}%.")
  if correct_label / total_label >= .99:
    break


Train Accuracy on 1 epoch is: 82.04384268214055%.
Train Accuracy on 2 epoch is: 94.51966473243068%.
Train Accuracy on 3 epoch is: 98.38813668600902%.
Train Accuracy on 4 epoch is: 99.38749194068343%.


In [198]:
test_email_label_pairs = [(x_test[idx], y_test[idx]) for idx in range(len(x_test))]

test_dataset = SpamEmailDataset(test_email_label_pairs, vocab, max_len)

test_dataloader = DataLoader(test_dataset, batch_size=16, shuffle=True)

In [199]:
model.eval()

total_label, correct_label = 0, 0

with torch.no_grad():
  for email, label in test_dataloader:
      email, label = email.to(device), label.to(device)

      output = model(email)
      predicted = (output.squeeze() > 0.5).float()
      total_label += label.size(0)
      correct_label += (predicted == label).sum().item()


print(f"Test Accuracy is: {100 * correct_label / total_label}%")


Test Accuracy is: 97.87336877718705%


## Let's try with DropOut

In [200]:
class SpamDetectorModelWithDropOut(nn.Module):
  def __init__(self, embed_size) -> None:
    super(SpamDetectorModelWithDropOut, self).__init__()
    self.embedding = nn.Embedding(len(vocab), embed_size)
    self.lstm = nn.LSTM(embed_size, 64, batch_first=True)
    self.fc = nn.Linear(64, 32)
    self.relu = nn.ReLU()
    self.drop = nn.Dropout(0.6)
    self.out = nn.Linear(32, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, x):
    embedded = self.embedding(x)
    lstm_out, _ = self.lstm(embedded)
    pooled = torch.max(lstm_out, 1)[0]
    pooled = self.drop(pooled)
    fc = self.fc(pooled)
    fc = self.drop(fc)
    out = self.out(fc)

    return self.sigmoid(out)



model = SpamDetectorModelWithDropOut(150)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = model.to(device)

In [201]:
model.train()

SpamDetectorModelWithDropOut(
  (embedding): Embedding(50523, 150)
  (lstm): LSTM(150, 64, batch_first=True)
  (fc): Linear(in_features=64, out_features=32, bias=True)
  (relu): ReLU()
  (drop): Dropout(p=0.6, inplace=False)
  (out): Linear(in_features=32, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [202]:
num_epoch = 18

for _ in range(num_epoch):
  correct_label, total_label = 0, 0
  for email, label in dataloader:
    email, label = email.to(device), label.to(device)

    output = model(email)

    predicted = (output.squeeze() > 0.5).float()
    total_label += label.size(0)
    correct_label += (predicted == label).sum().item()

    loss = criterion(output.squeeze(), label.float())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  print(f"Train Accuracy on {_+1} epoch is: {100*correct_label / total_label}%.")
  if correct_label / total_label >= .99:
    break


Train Accuracy on 1 epoch is: 70.43842682140554%.
Train Accuracy on 2 epoch is: 87.49194068343004%.
Train Accuracy on 3 epoch is: 94.84203739522889%.
Train Accuracy on 4 epoch is: 97.45325596389426%.
Train Accuracy on 5 epoch is: 98.32366215344939%.
Train Accuracy on 6 epoch is: 98.03352675693101%.
Train Accuracy on 7 epoch is: 98.87169568020632%.
Train Accuracy on 8 epoch is: 98.74274661508704%.
Train Accuracy on 9 epoch is: 99.22630560928434%.


In [203]:
test_email_label_pairs = [(x_test[idx], y_test[idx]) for idx in range(len(x_test))]

test_dataset = SpamEmailDataset(test_email_label_pairs, vocab, max_len)

test_dataloader = DataLoader(test_dataset, batch_size=16, shuffle=True)

In [204]:
model.eval()

total_label, correct_label = 0, 0

with torch.no_grad():
  for email, label in test_dataloader:
      email, label = email.to(device), label.to(device)

      output = model(email)
      predicted = (output.squeeze() > 0.5).float()
      total_label += label.size(0)
      correct_label += (predicted == label).sum().item()


print(f"Test Accuracy is: {100 * correct_label / total_label}%")


Test Accuracy is: 96.13339777670372%


## Let's try without the fc layer.

In [205]:
class SpamDetectorModelWithoutFc(nn.Module):
  def __init__(self, embed_size) -> None:
    super(SpamDetectorModelWithoutFc, self).__init__()
    self.embedding = nn.Embedding(len(vocab), embed_size)
    self.lstm = nn.LSTM(embed_size, 64, batch_first=True)
    # self.drop = nn.Dropout(0.6)
    self.out = nn.Linear(64, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, x):
    embedded = self.embedding(x)
    lstm_out, _ = self.lstm(embedded)
    pooled = torch.max(lstm_out, 1)[0]
    # pooled = self.drop(pooled)
    out = self.out(pooled)

    return self.sigmoid(out)



model = SpamDetectorModelWithoutFc(150)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = model.to(device)
model.train()

SpamDetectorModelWithoutFc(
  (embedding): Embedding(50523, 150)
  (lstm): LSTM(150, 64, batch_first=True)
  (out): Linear(in_features=64, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [206]:
num_epoch = 18

for _ in range(num_epoch):
  correct_label, total_label = 0, 0
  for email, label in dataloader:
    email, label = email.to(device), label.to(device)

    output = model(email)

    predicted = (output.squeeze() > 0.5).float()
    total_label += label.size(0)
    correct_label += (predicted == label).sum().item()

    loss = criterion(output.squeeze(), label.float())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  print(f"Train Accuracy on {_+1} epoch is: {100*correct_label / total_label}%.")
  if correct_label / total_label >= .99:
    break


Train Accuracy on 1 epoch is: 79.40038684719536%.
Train Accuracy on 2 epoch is: 93.97163120567376%.
Train Accuracy on 3 epoch is: 96.71179883945841%.
Train Accuracy on 4 epoch is: 98.1624758220503%.
Train Accuracy on 5 epoch is: 99.03288201160541%.


In [207]:
test_email_label_pairs = [(x_test[idx], y_test[idx]) for idx in range(len(x_test))]

test_dataset = SpamEmailDataset(test_email_label_pairs, vocab, max_len)

test_dataloader = DataLoader(test_dataset, batch_size=16, shuffle=True)

In [208]:
model.eval()

total_label, correct_label = 0, 0

with torch.no_grad():
  for email, label in test_dataloader:
      email, label = email.to(device), label.to(device)

      output = model(email)
      predicted = (output.squeeze() > 0.5).float()
      total_label += label.size(0)
      correct_label += (predicted == label).sum().item()


print(f"Test Accuracy is: {100 * correct_label / total_label}%")


Test Accuracy is: 97.00338327694539%
